l_english:
 # Comment
 text_empty:0 ""
 text:0 "Value"
 text_multiline:0 "Value\nNew line"
 text_with_colorful_text:0 "Colorful text: §RRed text§!"
 text_with_parameter:0 "Parameter: $<LR>KEY</LR>$ and $KEY_WITH_COLOR|Y$"
 text_with_scripted_variable_reference:0 "Scripted variable: $@sv$"
 text_with_command:0 "Command: [<SYSTEM_COMMAND_SCOPE>Root</SYSTEM_COMMAND_SCOPE><OPERATOR>.</OPERATOR><COMMAND_SCOPE>Owner</COMMAND_SCOPE><OPERATOR>.</OPERATOR><COMMAND_SCOPE_LINK_PREFIX>event_target:</COMMAND_SCOPE_LINK_PREFIX><DYNAMIC_VALUE><COMMAND_SCOPE_LINK_VALUE>some_event_target</COMMAND_SCOPE_LINK_VALUE></DYNAMIC_VALUE><OPERATOR>.</OPERATOR><COMMAND_FIELD>GetName</COMMAND_FIELD>]  [<DR><COMMAND_FIELD_VALUE>some_scripted_loc</COMMAND_FIELD_VALUE></DR>] [<VARIABLE><COMMAND_FIELD_VALUE>some_variable</COMMAND_FIELD_VALUE></VARIABLE>]"
 text_with_icon:0 "Icon: £unity£ and £leader_skill|3£"
 text_with_concept_command:0 "Concept: ['concept', concept text] ['<DATABASE_OBJECT_TYPE>civic</DATABASE_OBJECT_TYPE><MARKER>:</MARKER><DR><DATABASE_OBJECT>some_civic</DATABASE_OBJECT></DR>']"
 text_with_text_format:0 "Text format: #v text#!"
 text_with_text_icon:0 "Text icon: @icon!"
